### ISSUE TITLE
64강까지 만들어주세요 👍 

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#11]
너무 재미있을 것 같아요 ~~ 🤗

**Comment by rlfrkdms1** [comment]
저희 FISA 근처의 맛집만을 다루는 서비스이기 때문에 일단 16강까지를 선정했습니다 !
직접 맛집들 찾아보고 64강 까지 추진해보겠습니다 👍
좋은 의견 감사합니다 !
