### ISSUE TITLE
[리뷰에 관한 궁금 증!]

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#12]
![리뷰작성부분]()
<img src="https://github.com/user-attachments/assets/7eeedb65-6895-4382-9f10-20f042457855" width="400" height="200"/>
리뷰 작성하는 텍스트부분이 사이즈 조절이 되게 끔 한 것 같은데 일부러 그렇게 하신건가용? ❓

**Comment by min20ta** [comment]
앗..사이즈 조절 안되게 끔 수정해보겠습니다. 알려주셔서 감사합니다!
