### ISSUE TITLE
잘 만드셨네요!  질문 3가지 있습니다.

### ISSUE THREAD

**Issue by bw02184** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#14]
1. 도시락 먹을 장소 추천 or 같이 점심 먹을 사람 구하는? 기능도 구현하면 재밌을 것 같아요 :웃음:  
2. readme의 3개의 성능 측정 부분에서 어느 페이지에 어느 성능인지 궁금합니다
3. 리뷰 작성부분은 추후에 자바스크립트로 구현하실 지 궁금합니다!

**Comment by SeungAh-Yoo99** [comment]
:웃음: 😊

**Comment by rlfrkdms1** [comment]
1. 좋은 기능같습니다 ! 특히 같이 점심 먹을 사람을 구하는 기능은 적극적으로 검토해보겠습니다 !!
2. 성능은 페이지 순서대로 표기하였는데 제목 추가하도록 하겠습니다 !
3. 네 그렇습니다 !!

좋은 의견 너무 감사합니다 !! 👍
