### ISSUE TITLE
통계 화면있으면 좋을 것 같아요 👍 

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#15]
음식 승률 통계 그래프 있으면 좋을 것 같아요~~

그리고 만약에 회원가입을 구현할 계획이라면
추천 시스템(코사인 유사도, 협업 필터링 등)도 있으면 좋을 것 같아요!!

**Comment by min20ta** [comment]
좋은 의견 감사합니다! 고려해서 추가해보겠습니다!
