### ISSUE TITLE
ppl-review

### ISSUE THREAD

**Issue by jyp-on** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#16]
- 좋은점
지도로 위치를 한눈에 파악할 수 있는점이 좋은 것 같아요.
- 개선하면 좋을점
음식점 대결 시 뒤로가기 버튼이 있으면 좋을 것 같아요.

**Comment by ksp0814** [comment]
감사합니다! 뒤로 가기 버튼 적용해보겠습니다!!
