### ISSUE TITLE
기능이 현실적으로 쓰기 좋은 것 같습니다. 약간의 issue 제안 드립니다!

### ISSUE THREAD

**Issue by jihyuk0414** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#17]
1. 메인 페이지 아래 버튼 가운데 정렬, 
2. 상세 페이지 영업 시간과 메뉴 정보, 사진 좌, 우 정렬 등 
일관된 정렬이 있으면 조금 더 보기 편할 것 같습니다!

**Comment by rlfrkdms1** [comment]
1. 메인 페이지 아래 버튼은 가운데 정렬이 되어있습니다 !
2. 영업시간과 메뉴 정렬등의 좌우 정렬은 저희가 사실 의도한 디자인이긴했습니다만 ㅜㅜ 말씀하신 부분도 고려해보겠습니다 !

좋은 의견 감사합니다 !
