### ISSUE TITLE
메뉴 정보 관련해서 질문하고 싶어요~

### ISSUE THREAD

**Issue by yaejinkong** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#18]
지금은 메뉴 정보나 운영시간을 수기로 작성하셨는데 이후에는 어떻게 정보들을 가져와서 보여주실 건가요 !? 
궁금합니다!

**Comment by ksp0814** [comment]
네이버나 구글을 통해서 상암동 근처 맛집을 크롤링해서 모은 정보를 보여드릴 예정입니다!
