### ISSUE TITLE
재밌을 것 같아요!! 질문 하나 있습니다!

### ISSUE THREAD

**Issue by hyeri1126** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#19]
디비는 어떤것을 사용하실 예정이신가요?
그리고 메인에서 라운드 선택 할 때 커서가 포인터로 바뀌면 더 좋을 것 같습니다!

**Comment by rlfrkdms1** [comment]
1. DB는 정해진 것이 없는데, 아마 MySQL이나 오라클 사용할 것 같습니다.
2. hover를 이용해서 선택할 때 선택되고 있다는 의미를 주고자 했는데, 포인터도 고려해보겠습니다.

좋은 의견 감사합니다 ! 👍
