### ISSUE TITLE
(질문 2개)잘봤습니다 앞으로 점심메뉴를 고를때 걱정이 덜할 것 같아요:)

### ISSUE THREAD

**Issue by my123dsa** [woorifisa-service-dev-3rd/frontend-1st-lunch_worldcup#20]
1. 리뷰작성시 작성자의  방문횟수를 추가하면 정보 신뢰성에 도움이 될 것 같음.

2. 오른쪽 음식 선택 시 사진의 중앙부 ### 부근에서 클릭이 되지 않는 구간 발생

**Comment by ksp0814** [comment]
1. 새로운 아이디어 감사합니다!! 적용시켜보겠습니당

2. 아직 데모 데이터라 문제가 좀 있는거 같습니다! 이후에 잘 작동하도록 노력하겠습니다!!!
